services:
   backend:
      build: .
      ports:
         - "8001:8001"
      depends_on:
         mongodb:
            condition: service_healthy
      entrypoint: ["/bin/sh", "-c", "tsx /app/src/seeders/user.seeder.ts && pnpm start"]

   mongodb:
      image: mongo
      ports:
         - "27017:27017"
      # environment:
      # - MONGO_INITDB_ROOT_USERNAME=be_hpai
      # - MONGO_INITDB_ROOT_PASSWORD=password
      healthcheck:
         test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
         interval: 10s
         timeout: 10s
         retries: 5
         start_period: 40s
      volumes:
         - mongodb_data:/data/db

volumes:
   mongodb_data:
